server:
  port: 9000
spring:
  application:
    name: xhlj-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # 网关路由配置
        - id: service-chat # 路由 id,自定义，只要唯一即可
          uri: lb://service-chat #负载均衡
          predicates:
            - Path=/*/chat/** #选择路径 以/chat/..开头，路径断言#
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/service/user/**