server:
  port: 8500

spring:
  application:
    name: service-chat
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

xhlj:
  chat:
    apiKey: SMcQAdGStVsfZ1iGrbDbjGjw
    secretKey: kiD7bsUbMZdF6BdvZGBDHgYsszGCZz3r